services:
    _defaults:
        autoconfigure: true


    numero2\StructuredDataBundle\Controller\ContentElement\StructuredDataController:
        arguments:
            - '@contao.routing.scope_matcher'
            - '@contao.routing.response_context_accessor'